#!/bin/sh

if [ SunOS = `uname` ]
then
  DEBVER=0
else
  if [ -f /etc/SuSE-release ]
  then
    DEBVER=-1
  else
    DEBVER=$(cut -d " " -f 1 /etc/debian_version)
  fi
fi

echo -n "running configuration for debian version $DEBVER "
chmod u+x Makefile.dist

case "$DEBVER" in
  0)
    echo "Solaris"
    aclocal
    autoconf
    autoheader
    automake -a --foreign
    ./configure $@
    ;;

  *)
    echo "debian or SuSE"
    ./Makefile.dist all
    ./configure --prefix=/usr $@
    ;;
esac

exit 0
