#line 2 "lexical.cxx"

#line 4 "lexical.cxx"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 32
#define YY_END_OF_BUFFER 33
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[353] =
    {   0,
       30,   30,   12,   12,   20,   20,    0,    0,   25,   25,
       33,   31,   30,   30,   31,   17,   31,   31,   15,   31,
       17,   14,   14,   14,   14,   14,   14,   32,   12,   13,
       15,   14,   14,   14,   20,   32,   15,   14,   32,   29,
       15,   14,   25,   26,   15,   14,    0,    0,   30,    0,
       23,    0,    0,   24,   28,   15,   16,   14,   14,   14,
       14,   14,   14,   14,   14,   12,   15,   14,   14,   11,
       14,   20,   21,    0,   21,   15,   14,    0,   29,   15,
       14,   25,   26,   26,   27,   15,   14,    0,    0,    0,
       23,    0,   23,   24,   24,    0,    0,    0,    0,    0,

       14,   14,    4,   14,    3,   14,   14,   14,   14,   14,
        0,   21,   21,   21,    0,   18,    0,    0,    0,    0,
       23,   18,    0,    0,    0,   24,   24,    0,    0,    0,
        0,    0,   14,    6,   14,    0,   14,   14,   14,   10,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,    0,    0,    0,   23,   24,   24,    0,    0,    0,
        0,    0,    2,   14,    0,   14,   14,    9,    0,    0,
        0,    0,   22,    0,    0,    0,   23,    0,   24,   24,
        0,    0,   19,    0,    0,   14,    0,    0,    0,    0,
        1,    7,    0,    0,    0,    0,    0,    0,   24,   24,

        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,   24,    0,    0,
        0,    0,    5,    0,    4,    0,    3,    0,    0,    0,
        0,    0,    0,    0,   23,   24,   24,    0,    0,    0,
        0,    6,    0,    0,    0,    0,    0,    0,   24,   24,
        0,    0,    8,    0,    0,    0,    0,    0,    0,   24,
       24,    0,    8,    0,    7,    0,    0,    0,    0,   24,
       24,    8,    0,    0,    0,    0,    0,    0,   24,   24,
        0,    0,    5,    0,    0,    0,    0,   24,   24,    0,
        0,    0,    0,    0,    0,   24,   24,    0,    0,    0,

        0,    0,    0,   24,   24,    0,    0,    0,    0,    0,
        0,   24,   24,    0,    0,    0,    0,    0,    0,   24,
       24,    0,    0,    0,    0,    0,    0,   24,   24,    0,
        0,    0,    0,    0,   24,   24,    0,    0,    0,    0,
       24,   24,    0,    0,    0,   24,   24,    0,   24,    0,
        0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    8,    1,    9,
       10,   11,    1,    8,   12,    1,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
        8,    1,    8,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   21,   29,   21,   30,   31,   32,   33,
       34,   35,   21,   36,   37,   38,   39,   40,   21,   41,
       21,   21,   42,    1,   43,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    3,    4,    4,    1,    5,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[367] =
    {   0,
        0,    0,   43,    0,   86,    0,  129,    0,  172,    0,
      934,  924,  214,  222,  219,  923,  935,  222,  225,  221,
      935,  240,  900,  901,  199,  258,  903,  935,  283,  935,
      272,    0,  897,  264,    0,  279,  279,  302,  924,  935,
      343,  358,    0,  284,  284,  401,  917,  915,  345,  442,
      915,  443,  920,  917,  445,  443,  912,    0,  898,  882,
      883,  886,  878,  429,  891,  350,  286,    0,  885,    0,
      887,    0,  935,  907,  456,  434,    0,  908,  935,  459,
        0,    0,  340,  453,  935,  456,    0,  900,  485,  474,
      899,  526,  935,    0,  451,  474,  478,  902,  876,  874,

      868,  866,    0,  865,    0,  886,  862,  862,  877,  866,
      454,  455,  885,  486,    0,  935,  508,  862,  852,  567,
        0,  891,  521,  472,  490,  862,  860,  860,  858,  877,
      862,  856,  849,    0,  856,  491,  860,  849,  845,    0,
      850,  848,  848,  846,  857,  534,  549,  843,  832,  553,
      559,  572,  511,  491,  831,  847,  841,  845,  839,  857,
      827,  843,    0,  834,  509,  827,  828,    0,  837,  831,
      835,  829,  935,  576,  822,  593,  597,  254,  817,  833,
      815,  831,  935,  830,  819,  830,  556,  581,  494,  533,
        0,    0,  810,  826,  808,  824,  809,  544,  822,  811,

      820,  809,  808,  808,  805,  523,  578,  574,  447,  583,
      815,  804,  813,  802,  613,  619,  801,  801,  799,  799,
      798,  803,    0,  595,  820,  597,  819,  599,  793,  793,
      791,  791,  623,  641,  645,  790,  795,  788,  793,  792,
      629,  809,  610,  620,  784,  789,  782,  787,  786,  807,
      784,  650,  651,  489,  632,  783,  804,  781,  802,  801,
      768,  661,  665,  650,  795,  798,  765,  796,  763,  762,
      768,  669,  767,  642,  759,  765,  757,  763,  762,  762,
      760,  760,  779,  757,  757,  755,  755,  754,  747,  752,
      745,  750,  743,  748,  741,  740,  769,  738,  767,  736,

      765,  721,  727,  713,  686,  700,  681,  698,  675,  695,
      673,  675,  671,  673,  669,  668,  660,  666,  658,  664,
      661,  662,  659,  653,  660,  651,  658,  654,  652,  652,
      650,  653,  671,  650,  644,  636,  636,  628,  652,  601,
      578,  589,  555,  506,  503,  503,  401,  343,  304,  240,
      216,  935,  706,  710,  216,  715,  720,  725,  730,  735,
      740,  744,  749,  754,  759,  764
    } ;

static yyconst flex_int16_t yy_def[367] =
    {   0,
      352,    1,  352,    3,  352,    5,  352,    7,  352,    9,
      352,  353,  353,  353,  354,  353,  352,  352,  353,  353,
      352,  352,   22,   22,   22,   22,   22,  352,  352,  352,
      352,  355,  355,  355,  356,  357,  356,  352,  358,  352,
      358,  352,  359,  360,  359,  352,  353,  361,  353,  354,
      353,  362,  363,  364,  352,  353,  353,   22,   22,   22,
       22,   22,   22,   22,   22,  352,  352,  355,  355,  355,
      355,  356,  352,  352,  357,  356,   38,  358,  352,  358,
       42,  359,  360,  360,  352,  359,   46,  361,  352,  362,
      361,  363,  352,  364,  364,  352,  352,  352,  352,  352,

       22,   22,   22,   22,   22,   22,   22,   22,  355,  355,
      352,  352,  352,  357,   89,  352,  352,  352,  365,  363,
       89,  363,  363,  363,  366,  364,  364,  352,  352,  352,
      352,  352,   22,   22,   22,  353,   22,   22,  355,  355,
      352,  352,  352,  352,  352,  352,  352,  352,  365,  363,
      352,  363,  363,  366,  365,  364,  364,  352,  352,  352,
      352,  352,   22,   22,  353,   22,   22,  355,  352,  352,
      352,  352,  352,  352,  352,  363,  352,  363,  364,  364,
      352,  352,  352,  352,  352,   22,  353,  353,  353,  353,
       22,   22,  352,  352,  352,  352,  352,  363,  364,  364,

      352,  352,  352,  352,   22,  353,  353,  353,  353,  353,
      352,  352,  352,  352,  352,  363,  364,  364,  352,  352,
      352,  352,   22,  353,  353,  353,  353,  353,  352,  352,
      352,  352,  352,  363,  352,  364,  364,  352,  352,  352,
      352,  353,  353,  353,  352,  352,  352,  352,  364,  364,
      352,  352,  352,  353,  353,  352,  352,  352,  352,  364,
      364,  352,  352,  353,  353,  352,  352,  352,  352,  364,
      364,  352,  352,  353,  352,  352,  352,  352,  364,  364,
      352,  352,  353,  352,  352,  352,  352,  364,  364,  352,
      352,  352,  352,  352,  352,  364,  364,  352,  352,  352,

      352,  352,  352,  364,  364,  352,  352,  352,  352,  352,
      352,  364,  364,  352,  352,  352,  352,  352,  352,  364,
      364,  352,  352,  352,  352,  352,  352,  364,  364,  352,
      352,  352,  352,  352,  364,  364,  352,  352,  352,  352,
      364,  364,  352,  352,  352,  364,  364,  352,  364,  352,
      352,    0,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352
    } ;

static yyconst flex_int16_t yy_nxt[979] =
    {   0,
       12,   13,   14,   13,   13,   12,   15,   16,   17,   12,
       12,   12,   18,   19,   19,   20,   21,   16,   12,   16,
       22,   22,   22,   23,   22,   22,   22,   22,   22,   22,
       24,   25,   22,   22,   22,   22,   26,   22,   22,   27,
       22,   16,   16,   28,   29,   30,   28,   29,   28,   28,
       28,   28,   28,   28,   28,   28,   31,   31,   28,   28,
       28,   28,   28,   32,   33,   32,   32,   32,   32,   32,
       32,   34,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   28,   28,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   36,   37,

       37,   35,   35,   35,   35,   35,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   35,   35,   39,
       39,   40,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   41,   41,   39,   39,   39,   39,   39,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       39,   39,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   44,   43,   43,   45,   45,   43,   43,   43,
       43,   43,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   43,   43,   49,   49,   49,   49,   68,
       61,   51,   48,   49,   49,   49,   49,   52,  183,   48,
       48,   53,   54,   48,   55,   53,   57,   62,   56,   56,
       47,   47,   47,   47,   47,   47,   47,   47,   48,   47,
       47,   47,  183,   58,   58,   47,   93,   47,   47,   47,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   47,   47,   63,   66,   67,   67,   66,   70,   74,
      198,   75,   76,   76,   84,   64,   85,   86,   86,   67,

       67,   71,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,  351,   77,   77,   72,   72,   72,
       72,   72,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   72,   72,   79,   49,   49,   49,   49,
      352,   66,  352,   48,   66,  173,   80,   80,   78,   78,
       79,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   81,   81,   78,   78,   78,   78,   78,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   78,

       78,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,  350,   82,   82,   87,   87,   82,   82,   82,   82,
       82,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   82,   82,   51,   91,   96,   76,   76,   97,
       52,   48,   92,  106,   53,   48,   56,   56,   53,   53,
      112,   79,   98,   84,  107,   85,   74,  113,  114,   86,
       86,   99,   80,   80,   93,   96,   91,  126,   96,   96,
      141,  143,   96,   92,  227,  100,  115,  115,  115,  115,
       53,  127,  155,  155,  142,  144,   74,   48,  114,   48,

       99,  116,   48,  117,  128,  153,  165,  349,  118,  146,
      146,  146,  146,   93,  100,  173,  348,   48,  129,  209,
      264,  147,  150,  151,  150,  150,  119,  120,  121,  120,
      120,   48,  122,  122,  152,  146,  146,  146,  146,  187,
      188,   48,  122,  178,  123,  189,   93,  147,  190,  124,
      174,  174,  174,  174,  150,  151,  150,  150,  210,  224,
      146,  146,  146,  146,   48,  116,  152,  125,  120,  121,
      120,  120,  147,  176,  177,  176,  176,  174,  174,  174,
      174,  216,   48,  122,  206,  123,   48,  183,  122,   48,
      124,   48,  116,  347,  176,  177,  176,  176,  174,  174,

      174,  174,  207,   48,  226,   48,  228,   48,  125,  122,
      346,  345,  225,  116,  233,  233,  233,  233,   48,  208,
      234,  235,  234,  234,  233,  233,  233,  233,   48,  116,
      253,  117,  242,  253,  243,  122,  244,  123,  254,  116,
       48,  117,  234,  235,  234,  234,  233,  233,  233,  233,
       48,  253,  253,  255,  263,  253,  344,  122,   48,  123,
      183,  116,  253,  117,  343,  272,  253,  265,  342,  253,
      253,  274,  341,  253,  173,  340,  283,  339,  338,  337,
      336,  335,  173,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,

      317,  273,  316,  315,  314,  281,   47,   47,  313,   47,
       50,   50,   50,   50,   50,   72,   72,  312,   72,   72,
       73,   73,   73,   73,   73,   78,   78,   78,   78,   78,
       82,  311,   82,   82,   82,   83,   83,   83,   83,   83,
       88,   88,   88,   88,   90,   90,   90,   90,   90,   53,
       53,   53,   53,   53,   94,  310,   94,   94,   94,  149,
      149,  149,  149,  149,  154,  154,  154,  154,  154,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,   48,  291,  290,
      289,  288,  287,  286,  285,  284,  282,  280,  279,  278,

      277,  276,  275,   48,  271,  270,  269,  268,  267,  266,
      262,  261,  260,  259,  258,  257,  256,   48,  241,  252,
      251,  250,  249,  248,  247,  246,  245,   48,   48,  241,
      240,  239,  238,  237,  236,  232,  231,  230,  229,  223,
      222,  221,  220,  219,  218,  217,  215,  214,  213,  212,
      211,  205,  204,  203,  202,  201,  200,  199,  197,  196,
      195,  194,  193,  192,  191,  186,  185,  184,  183,  182,
      181,  180,  179,  116,  116,  175,  173,  172,  171,  170,
      169,  168,  167,  166,  164,  163,  162,  161,  160,  159,
      158,  157,  156,   93,  116,  148,  145,  140,  139,  138,

      137,  136,  135,  134,  133,  132,  131,  130,   89,   89,
       79,  111,  110,  109,  108,  105,  104,  103,  102,  101,
       48,   95,   93,   48,   89,   48,   79,   69,   65,   60,
       59,   48,   48,  352,   11,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352
    } ;

static yyconst flex_int16_t yy_chk[979] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,   13,   13,   13,   13,  355,
       25,   15,   13,   14,   14,   14,   14,   15,  351,   20,
       14,   15,   18,   19,   18,   15,   20,   25,   19,   19,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,  350,   22,   22,   22,  178,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   26,   29,   31,   31,   29,   34,   36,
      178,   36,   37,   37,   44,   26,   44,   45,   45,   67,

       67,   34,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,  349,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   41,   49,   49,   49,   49,
       83,   66,   83,   49,   66,  348,   41,   41,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,

       42,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,  347,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   50,   52,   55,   76,   76,   55,
       50,   56,   52,   64,   50,  209,   56,   56,   50,   52,
       75,   80,   55,   84,   64,   84,   75,   75,   75,   86,
       86,   55,   80,   80,  124,   96,   90,   95,   96,   97,
      111,  112,   97,   90,  209,   55,   89,   89,   89,   89,
       90,   95,  125,  154,  111,  112,  114,  254,  114,  136,

       96,   89,  189,   89,   97,  124,  136,  346,   89,  117,
      117,  117,  117,  153,   96,  345,  344,  165,   97,  189,
      254,  117,  123,  123,  123,  123,   89,   92,   92,   92,
       92,  206,  125,  154,  123,  146,  146,  146,  146,  165,
      165,  190,   92,  153,   92,  165,  198,  146,  165,   92,
      147,  147,  147,  147,  150,  150,  150,  150,  190,  206,
      151,  151,  151,  151,  187,  147,  150,   92,  120,  120,
      120,  120,  151,  152,  152,  152,  152,  174,  174,  174,
      174,  198,  208,  120,  187,  120,  207,  343,  152,  188,
      120,  210,  174,  342,  176,  176,  176,  176,  177,  177,

      177,  177,  188,  224,  208,  226,  210,  228,  120,  176,
      341,  340,  207,  177,  215,  215,  215,  215,  243,  188,
      216,  216,  216,  216,  233,  233,  233,  233,  244,  215,
      241,  215,  224,  241,  226,  216,  228,  216,  243,  233,
      255,  233,  234,  234,  234,  234,  235,  235,  235,  235,
      274,  252,  253,  244,  252,  253,  339,  234,  264,  234,
      338,  235,  262,  235,  337,  262,  263,  255,  336,  263,
      272,  264,  335,  272,  334,  333,  274,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,

      309,  263,  308,  307,  306,  272,  353,  353,  305,  353,
      354,  354,  354,  354,  354,  356,  356,  304,  356,  356,
      357,  357,  357,  357,  357,  358,  358,  358,  358,  358,
      359,  303,  359,  359,  359,  360,  360,  360,  360,  360,
      361,  361,  361,  361,  362,  362,  362,  362,  362,  363,
      363,  363,  363,  363,  364,  302,  364,  364,  364,  365,
      365,  365,  365,  365,  366,  366,  366,  366,  366,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  273,  271,  270,  269,

      268,  267,  266,  265,  261,  260,  259,  258,  257,  256,
      251,  250,  249,  248,  247,  246,  245,  242,  240,  239,
      238,  237,  236,  232,  231,  230,  229,  227,  225,  222,
      221,  220,  219,  218,  217,  214,  213,  212,  211,  205,
      204,  203,  202,  201,  200,  199,  197,  196,  195,  194,
      193,  186,  185,  184,  182,  181,  180,  179,  175,  172,
      171,  170,  169,  167,  166,  164,  162,  161,  160,  159,
      158,  157,  156,  155,  149,  148,  145,  144,  143,  142,
      141,  139,  138,  137,  135,  133,  132,  131,  130,  129,
      128,  127,  126,  122,  119,  118,  113,  110,  109,  108,

      107,  106,  104,  102,  101,  100,   99,   98,   91,   88,
       78,   74,   71,   69,   65,   63,   62,   61,   60,   59,
       57,   54,   53,   51,   48,   47,   39,   33,   27,   24,
       23,   16,   12,   11,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.lxx"
/*
  flexconf - flexible configuration generator
  Copyright (C) 2003-2008 Holger Böhnke

  This file is part of flexconf.

  Flexconf is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#line 24 "lexical.lxx"
#ifdef _MSC_VER
  #pragma warning(disable: 4996)
  #define YY_NO_UNISTD_H
  #include <io.h>
#endif

  #include "yystype.h"
  #include "grammar.h"
  #include <stdio.h>

  #define YY_NO_UNPUT
  #define YY_STACK_USED     0
  #define YY_MAIN           0

//  #define ECHOTOK(tok)    printf("tok TOK_%s, text: <%.*s>\n", #tok, yyleng, yytext);
//  #define ECHOOUT(out)    printf("out %s, text: <%.*s>\n", #out, yyleng, yytext);
//  #define ECHOFKT(out)    printf("out %s, text: <%.*s>\n", #out, yyleng, yytext);
//  #define ECHOCMT(out)    printf("out %s, text: <%.*s>\n", #out, yyleng, yytext);
//  #define ECHOSX(out)     printf("out %s, text: <%.*s>\n", #out, yyleng, yytext);
//  #define ECHOWS          printf("text: <WS{%d}>\n", yyleng);

#ifndef ECHOTOK
  #define ECHOTOK(tok)
#endif

#ifndef ECHOOUT
  #define ECHOOUT(out)
#endif

#ifndef ECHOFKT
  #define ECHOFKT(out)
#endif

#ifndef ECHOCMT
  #define ECHOCMT(out)
#endif

#ifndef ECHOSX
  #define ECHOSX(out)
#endif

#ifndef ECHOWS
  #define ECHOWS
#endif




#line 862 "lexical.cxx"

#define INITIAL 0
#define SC_STRUCTXML 1
#define SC_SKIP 2
#define SC_OLCOMMENT 3
#define SC_BRCOMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 87 "lexical.lxx"


#line 1056 "lexical.cxx"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 353 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 935 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 89 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(STRUCT);
    return TOK_STRUCT;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 95 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(CLASS);
    return TOK_CLASS;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 101 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(SET);
    return TOK_SET;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(MAP);
    return TOK_MAP;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(MAP);
    return TOK_MAP;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 119 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(LIST);
    return TOK_LIST;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(VECTOR);
    return TOK_VECTOR;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 133 "lexical.lxx"
{
    BEGIN(SC_STRUCTXML);
    ECHOSX(STRUCTXML_BEGIN);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 138 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(SC_STRUCTXML_ALIAS);
    return TOKSX_ALIAS;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 144 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(SC_STRUCTXML_ITEM);
    return TOKSX_ITEM;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 150 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(SC_STRUCTXML_ID);
    return TOKSX_ID;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 156 "lexical.lxx"
{
    ECHOWS;
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 160 "lexical.lxx"
{
    ECHOSX(SC_STRUCTXML_END);
    BEGIN(INITIAL);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 167 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(IDENT);
    return TOK_IDENT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 175 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(NUM);
    return TOK_NUM;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 183 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(NSSEP);
    return TOK_NSSEP;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 191 "lexical.lxx"
{
    yylval.assign(yytext, yyleng);
    ECHOTOK(CHAR);
    return *yytext;
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 199 "lexical.lxx"
{
    /* skip functions and inline functions */
    /*
      this regex allows differences to legal C++. If illegal C++ is
      matched it doesn't matter. The compiler takes care of it.
      However some legal C++ may not be matched, specially when
      comments or string constants containing brackets are in the
      middle of the declaration. Simply avoid any function specific
      special chars like [(){};] inside comments or string constants.
      Rewrite the code if necessary. This should be possible in 99%
      of the cases. In any other case use the skip tags below.
    */
    ECHOFKT(FUNCTION);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 216 "lexical.lxx"
{
    /* start skipped section */
    ECHOOUT(beginskip);
    BEGIN(SC_SKIP);
}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 222 "lexical.lxx"
{
    /* skip all but '/' */
    ECHOOUT(skip);
}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 227 "lexical.lxx"
{
    /* skip '/', if not followed by a '*' */
    ECHOOUT(skip_slash);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 233 "lexical.lxx"
{
    /* end skipped section */
    ECHOOUT(endskip);
    BEGIN(INITIAL);
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 241 "lexical.lxx"
{
    /* skip preprocessor directives */
    ECHOOUT(CPP);
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 248 "lexical.lxx"
{
    /* start c braced comments */
    ECHOCMT(begincmt);
    BEGIN(SC_BRCOMMENT);
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 254 "lexical.lxx"
{
    ECHOCMT(incmt_not_star);
}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 258 "lexical.lxx"
{
    ECHOCMT(incmt_star);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 262 "lexical.lxx"
{
    ECHOCMT(endcmt);
    BEGIN(INITIAL);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 268 "lexical.lxx"
{
    /* start c++ one line comments */
    ECHOCMT(OLCOMMENT);
    BEGIN(SC_OLCOMMENT);
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 274 "lexical.lxx"
{
    /* remove one line comments until NL */
    ECHOCMT(EAT_EOL);
    BEGIN(INITIAL);
}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 282 "lexical.lxx"
{
    /* skip whitespace */
    ECHOWS;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 287 "lexical.lxx"
{
    /* anything else is an error */
    printf("flex discovered an error: <%.*s>\n", yyleng, yytext);
    return -1;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 293 "lexical.lxx"
ECHO;
	YY_BREAK
#line 1429 "lexical.cxx"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SC_STRUCTXML):
case YY_STATE_EOF(SC_SKIP):
case YY_STATE_EOF(SC_OLCOMMENT):
case YY_STATE_EOF(SC_BRCOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 353 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 353 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 352);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 293 "lexical.lxx"



